package com.drppp.drtech.common.drone.program.compile;

public enum DroneDiagnosticCode {
    TOO_MANY_NODES,
    TOO_MANY_EDGES,
    UNKNOWN_NODE_TYPE,
    EXTENSION_UNAVAILABLE,
    NO_ENTRY_NODE,
    MULTIPLE_ENTRY_NODES,
    UNKNOWN_SOURCE_NODE,
    UNKNOWN_TARGET_NODE,
    UNKNOWN_SOURCE_PORT,
    UNKNOWN_TARGET_PORT,
    INVALID_EDGE_DIRECTION,
    INCOMPATIBLE_PORT_TYPES,
    TOO_MANY_PORT_CONNECTIONS,
    REQUIRED_PORT_NOT_CONNECTED,
    DUPLICATE_CONNECTION,
    INVALID_NODE_CONFIGURATION,
    AREA_LIMIT_EXCEEDED,
    UNREACHABLE_NODE,
    NO_EXIT_LOOP,
    POSSIBLE_INFINITE_LOOP,
    REQUIRED_UPGRADE_MISSING,
    CHASSIS_TIER_RECOMMENDED,
    VOLTAGE_TIER_MISMATCH
}
