package com.drppp.drtech.common.drone.program.compile;

public enum DroneDiagnosticCode {
    TOO_MANY_NODES,
    TOO_MANY_EDGES,
    UNKNOWN_NODE_TYPE,
    NO_ENTRY_NODE,
    MULTIPLE_ENTRY_NODES,
    UNKNOWN_SOURCE_NODE,
    UNKNOWN_TARGET_NODE,
    UNKNOWN_SOURCE_PORT,
    UNKNOWN_TARGET_PORT,
    INVALID_EDGE_DIRECTION,
    INCOMPATIBLE_PORT_TYPES,
    TOO_MANY_PORT_CONNECTIONS,
    REQUIRED_PORT_NOT_CONNECTED,
    DUPLICATE_CONNECTION,
    INVALID_NODE_CONFIGURATION,
    UNREACHABLE_NODE
}
