package com.drppp.drtech.common.Items.MetaItems;

import gregtech.api.items.metaitem.MetaItem;

public final class DrMetaItems {
    public static MetaItem<?>.MetaValueItem ENERGY_ELEMENT_1;
    public static MetaItem<?>.MetaValueItem ENERGY_ELEMENT_2;
    public static MetaItem<?>.MetaValueItem ENERGY_ELEMENT_3;
    public static MetaItem<?>.MetaValueItem ENERGY_ELEMENT_4;
    public static MetaItem<?>.MetaValueItem ENERGY_ELEMENT_5;
    public static MetaItem<?>.MetaValueItem GRAVITY_SHIELD;
    public static MetaItem<?>.MetaValueItem SKULL_DUST;
    public static MetaItem<?>.MetaValueItem PIPIE_1;
    public static MetaItem<?>.MetaValueItem PIPIE_5;
    public static MetaItem<?>.MetaValueItem PIPIE_10;
    public static MetaItem<?>.MetaValueItem POS_CARD;
    public static MetaItem<?>.MetaValueItem GOLD_COIN;
    public static MetaItem<?>.MetaValueItem FLY_RING;
    public static MetaItem<?>.MetaValueItem LIFE_SUPPORT_RING;
    public static MetaItem<?>.MetaValueItem TACTICAL_LASER_SUBMACHINE_GUN;
    public static MetaItem<?>.MetaValueItem ELECTRIC_PLASMA_GUN;
    public static MetaItem<?>.MetaValueItem ADVANCED_TACHINO_DISRUPTOR;
    public static MetaItem<?>.MetaValueItem NUCLEAR_BATTERY_LV;
    public static MetaItem<?>.MetaValueItem NUCLEAR_BATTERY_MV;
    public static MetaItem<?>.MetaValueItem NUCLEAR_BATTERY_HV;
    public static MetaItem<?>.MetaValueItem TELEPATHIC_NECKLACE;
    public static MetaItem<?>.MetaValueItem WIRELESS_NETWORK_CONTROL_PANEL;
    public static MetaItem<?>.MetaValueItem HAND_PUMP;
    public static MetaItem<?>.MetaValueItem GRASS_KILLER;
    public static MetaItem<?>.MetaValueItem UPGRADE_NULL;
    public static MetaItem<?>.MetaValueItem UPGRADE_SPEED1;
    public static MetaItem<?>.MetaValueItem UPGRADE_SPEED2;
    public static MetaItem<?>.MetaValueItem UPGRADE_SPEED3;
    public static MetaItem<?>.MetaValueItem UPGRADE_SPEED4;
    public static MetaItem<?>.MetaValueItem UPGRADE_SPEED5;
    public static MetaItem<?>.MetaValueItem UPGRADE_SPEED6;
    public static MetaItem<?>.MetaValueItem UPGRADE_SPEED7;
    public static MetaItem<?>.MetaValueItem UPGRADE_SPEED8;
    public static MetaItem<?>.MetaValueItem UPGRADE_SPEED8P;
    public static MetaItem<?>.MetaValueItem UPGRADE_PRODUCTION;
    public static MetaItem<?>.MetaValueItem UPGRADE_PLAIN;
    public static MetaItem<?>.MetaValueItem UPGRADE_LIGHT;
    public static MetaItem<?>.MetaValueItem UPGRADE_FLOWERING;
    public static MetaItem<?>.MetaValueItem UPGRADE_WINTER_EMULATION;
    public static MetaItem<?>.MetaValueItem UPGRADE_DRYER;
    public static MetaItem<?>.MetaValueItem UPGRADE_AUTOMATION;
    public static MetaItem<?>.MetaValueItem UPGRADE_HUMIDIFIER;
    public static MetaItem<?>.MetaValueItem UPGRADE_HELL_EMULATION;
    public static MetaItem<?>.MetaValueItem UPGRADE_POLLEN_SCRUBBER;
    public static MetaItem<?>.MetaValueItem UPGRADE_DESERT_EMULATION;
    public static MetaItem<?>.MetaValueItem UPGRADE_COOLER;
    public static MetaItem<?>.MetaValueItem UPGRADE_LIFESPAN;
    public static MetaItem<?>.MetaValueItem UPGRADE_SEAL;
    public static MetaItem<?>.MetaValueItem UPGRADE_GENETIC_STABILIZER;
    public static MetaItem<?>.MetaValueItem UPGRADE_JUNGLE_EMULATION;
    public static MetaItem<?>.MetaValueItem UPGRADE_TERRITORY;
    public static MetaItem<?>.MetaValueItem UPGRADE_OCEAN_EMULATION;
    public static MetaItem<?>.MetaValueItem UPGRADE_OPEN_SKY;
    public static MetaItem<?>.MetaValueItem UPGRADE_HEATER;
    public static MetaItem<?>.MetaValueItem UPGRADE_SIEVE;
    public static MetaItem<?>.MetaValueItem UPGRADE_T;
    public static MetaItem<?>.MetaValueItem TOOL_BOX;
    public static MetaItem<?>.MetaValueItem MATRIX_GEMS;
    public static MetaItem<?>.MetaValueItem XJC;
    public static MetaItem<?>.MetaValueItem INULIN;
    public static MetaItem<?>.MetaValueItem NATURAL_RUBBER;
    public static MetaItem<?>.MetaValueItem RAPESEED_FLOWER;
    public static MetaItem<?>.MetaValueItem SNAPDRAGON;
    public static MetaItem<?>.MetaValueItem LUCKY_CLOVER;

    //  Fluid Cores
    public static MetaItem<?>.MetaValueItem FLUID_CORE_T1;
    public static MetaItem<?>.MetaValueItem FLUID_CORE_T2;
    public static MetaItem<?>.MetaValueItem FLUID_CORE_T3;
    public static MetaItem<?>.MetaValueItem FLUID_CORE_T4;
    public static MetaItem<?>.MetaValueItem FLUID_CORE_T5;
    public static MetaItem<?>.MetaValueItem FLUID_CORE_T6;
    public static MetaItem<?>.MetaValueItem FLUID_CORE_T7;
    public static MetaItem<?>.MetaValueItem FLUID_CORE_T8;
    public static MetaItem<?>.MetaValueItem FLUID_CORE_T9;
    public static MetaItem<?>.MetaValueItem FLUID_CORE_T10;

    // Fusion reactor parts
    public static MetaItem<?>.MetaValueItem FUSION_FIRST_WALL_PLATE;
    public static MetaItem<?>.MetaValueItem FUSION_MAGNET_COIL;
    public static MetaItem<?>.MetaValueItem FUSION_COOLING_CHANNEL;
    public static MetaItem<?>.MetaValueItem TRITIUM_BREEDING_CELL;
    public static MetaItem<?>.MetaValueItem NEUTRON_CAPTURE_CORE;
    public static MetaItem<?>.MetaValueItem MAGNETIC_FIELD_STORAGE_CELL;
    public static MetaItem<?>.MetaValueItem DT_FUEL_INJECTOR;
    public static MetaItem<?>.MetaValueItem RF_GENERATOR_CORE;
    public static MetaItem<?>.MetaValueItem RF_WAVEGUIDE;
    public static MetaItem<?>.MetaValueItem RF_PHASE_SYNCHRONIZER;
    public static MetaItem<?>.MetaValueItem CERAMIC_RF_WINDOW;

    // Loot Table
    public static MetaItem<?>.MetaValueItem LOOT_TABLE_TEST;
    public static MetaItem<?>.MetaValueItem LOOT_TABLE_STONE_AGE;
    public static MetaItem<?>.MetaValueItem LOOT_TABLE_STEAM_AGE;
    public static MetaItem<?>.MetaValueItem LOOT_TABLE_LV;
    public static MetaItem<?>.MetaValueItem LOOT_TABLE_MV;
    public static MetaItem<?>.MetaValueItem LOOT_TABLE_HV;
    public static MetaItem<?>.MetaValueItem LOOT_TABLE_EV;
    public static MetaItem<?>.MetaValueItem LOOT_TABLE_IV;
    public static MetaItem<?>.MetaValueItem LOOT_TABLE_LUV;
    public static MetaItem<?>.MetaValueItem LOOT_TABLE_ZPM;
    public static MetaItem<?>.MetaValueItem LOOT_TABLE_UV;
    public static MetaItem<?>.MetaValueItem LOOT_TABLE_UHV;
    public static MetaItem<?>.MetaValueItem LOOT_TABLE_AE1;
    public static MetaItem<?>.MetaValueItem LOOT_TABLE_AE2;
    public static MetaItem<?>.MetaValueItem LOOT_TABLE_BEE1;
    public static MetaItem<?>.MetaValueItem LOOT_TABLE_BEE2;
    public static MetaItem<?>.MetaValueItem LOOT_TABLE_BEE3;
    public static MetaItem<?>.MetaValueItem LOOT_TABLE_BM1;
    public static MetaItem<?>.MetaValueItem LOOT_TABLE_BM2;
    public static MetaItem<?>.MetaValueItem LOOT_TABLE_BM3;
    public static MetaItem<?>.MetaValueItem LOOT_TABLE_COMPUTER1;
    public static MetaItem<?>.MetaValueItem LOOT_TABLE_CROPS;
    public static MetaItem<?>.MetaValueItem LOOT_TABLE_FLOPPIES;
    public static MetaItem<?>.MetaValueItem LOOT_TABLE_FOOD1;
    public static MetaItem<?>.MetaValueItem LOOT_TABLE_FOOD2;
    public static MetaItem<?>.MetaValueItem LOOT_TABLE_FOOD3;
    public static MetaItem<?>.MetaValueItem LOOT_TABLE_FOOD4;
    public static MetaItem<?>.MetaValueItem LOOT_TABLE_FOREST1;
    public static MetaItem<?>.MetaValueItem LOOT_TABLE_FOREST2;
    public static MetaItem<?>.MetaValueItem LOOT_TABLE_FOREST3;
    public static MetaItem<?>.MetaValueItem LOOT_TABLE_GARDENS;
    public static MetaItem<?>.MetaValueItem LOOT_TABLE_HEE1;
    public static MetaItem<?>.MetaValueItem LOOT_TABLE_HEE2;
    public static MetaItem<?>.MetaValueItem LOOT_TABLE_LEGENDARY;
    public static MetaItem<?>.MetaValueItem LOOT_TABLE_MAGIC1;
    public static MetaItem<?>.MetaValueItem LOOT_TABLE_MAGIC2;
    public static MetaItem<?>.MetaValueItem LOOT_TABLE_MAGIC3;
    public static MetaItem<?>.MetaValueItem LOOT_TABLE_MAGIC4;
    public static MetaItem<?>.MetaValueItem LOOT_TABLE_MAGIC5;
    public static MetaItem<?>.MetaValueItem LOOT_TABLE_RAIL1;
    public static MetaItem<?>.MetaValueItem LOOT_TABLE_RAIL2;
    public static MetaItem<?>.MetaValueItem LOOT_TABLE_RAIL3;
    public static MetaItem<?>.MetaValueItem LOOT_TABLE_SEEDS;
    public static MetaItem<?>.MetaValueItem LOOT_TABLE_SPACE1;
    public static MetaItem<?>.MetaValueItem LOOT_TABLE_SPACE2;
    public static MetaItem<?>.MetaValueItem LOOT_TABLE_SPACE3;
    public static MetaItem<?>.MetaValueItem LOOT_TABLE_WITCH1;
    public static MetaItem<?>.MetaValueItem LOOT_TABLE_WITCH2;
    public static MetaItem<?>.MetaValueItem LOOT_TABLE_WITCH3;
    public static MetaItem<?>.MetaValueItem LOOT_TABLE_WITCH4;
    public static MetaItem<?>.MetaValueItem LOOT_TABLE_WITCH5;

    public static void MetaItemsInit() {
        MetaItems1 metaItem = new MetaItems1();
        metaItem.setRegistryName("meta_items");

        MetaItemLootTable metaItemLootTable = new MetaItemLootTable();
        metaItemLootTable.setRegistryName("loot_table");
    }
}
